### ISSUE TITLE
Allow to toggle off Lint on Change

### ISSUE THREAD

**Issue by samartioli** [AtomLinter/linter-tslint#184]
I have my global linter preferences set to Lint on Change === false

Still, linter-tslint is linting on change. I only want to lint on save. 

I'm sure people are used to it, but it's impossible for me to work with linting on change. 
Save is perfect. 

```
  linter:
    lintOnChange: false
  "linter-eslint":
    disableWhenNoEslintConfig: false
    fixOnSave: true
    globalNodePath: "/Users/sam/npm-global"
  "linter-tslint":
    fixOnSave: true
```
